import React from 'react';
import Link from 'next/link';
import Image from 'next/image';

export default function HowToUse() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-50">
      <main className="container mx-auto px-6 py-24">
        <h1 className="text-4xl font-bold text-center mb-12 bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-indigo-600">How to Use NexQR</h1>
        <p className="text-center text-gray-600 mb-12 max-w-2xl mx-auto">
          Creating your own QR code with NexQR is fast, secure, and effortless. Just follow these steps:
        </p>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">
          {/* Step 1 */}
          <div className="bg-white p-6 rounded-xl shadow-sm hover:shadow-md transition-shadow">
            <div className="mb-4">
              <div className="relative w-full h-64 max-w-xs mx-auto">
                <Image src="/illustrations/data-input.svg" alt="Enter Data" fill style={{objectFit: 'contain'}} />
              </div>
            </div>
            <h2 className="text-xl font-semibold text-gray-800 mb-4">1. Enter Your Data</h2>
            <ul className="text-gray-600 space-y-2">
              <li>• Website URL</li>
              <li>• Text message</li>
              <li>• Phone number</li>
              <li>• Email address</li>
              <li>• Wi-Fi credentials</li>
              <li>• Or any custom data</li>
            </ul>
          </div>

          {/* Step 2 */}
          <div className="bg-white p-6 rounded-xl shadow-sm hover:shadow-md transition-shadow">
            <div className="mb-4">
              <div className="relative w-full h-64 max-w-xs mx-auto">
                <Image src="/illustrations/customize.svg" alt="Customize QR Code" fill style={{objectFit: 'contain'}} />
              </div>
            </div>
            <h2 className="text-xl font-semibold text-gray-800 mb-4">2. Customize Your QR</h2>
            <ul className="text-gray-600 space-y-2">
              <li>• Set foreground/background colors</li>
              <li>• Choose QR size</li>
              <li>• Upload your logo or icon</li>
              <li>• Select error correction level</li>
            </ul>
          </div>

          {/* Step 3 */}
          <div className="bg-white p-6 rounded-xl shadow-sm hover:shadow-md transition-shadow">
            <div className="mb-4">
              <div className="relative w-full h-64 max-w-xs mx-auto">
                <Image src="/illustrations/download.svg" alt="Download QR" fill style={{objectFit: 'contain'}} />
              </div>
            </div>
            <h2 className="text-xl font-semibold text-gray-800 mb-4">3. Download & Share</h2>
            <ul className="text-gray-600 space-y-2">
              <li>• Download as PNG, SVG, or PDF</li>
              <li>• Share via link</li>
              <li>• Embed on your site</li>
              <li>• Instant generation</li>
            </ul>
          </div>
        </div>

        <div className="mt-12 text-center">
          <div className="inline-block bg-gradient-to-r from-blue-50 to-indigo-50 p-4 rounded-lg">
            <p className="text-gray-700">
              ✅ All QR codes generated by NexQR are secure, fast, and ad-free.
            </p>
          </div>
        </div>

        <div className="mt-12 text-center">
          <Link href="/" className="inline-block bg-blue-600 hover:bg-blue-700 text-white font-medium py-3 px-8 rounded-lg transition-colors">
            Try NexQR Now
          </Link>
        </div>
      </main>
    </div>
  );
}
